name = "Create smp modpack auto update version"
author = "memz1013"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41da57f02993b1d8308b2120a6417bbafdbb2b51e01c7d9f64efda42112df441"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
