name = "Create smp modpack auto update version"
author = "memz1013"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2e4a9e5c612648522e753ad06fd25da9d49055c5e1d69f090e44d2a600d9f8a"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
