name = "Create smp modpack auto update version"
author = "memz1013"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45616200f7c3deb2378097b9ff182a1c67a6f25a3a8c9b16f9abfa9164a25614"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
