name = "Create smp modpack auto update version"
author = "memz1013"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79b49c40092db7f6029a3ccb4f9fad4c736b30ef2a95c6cb66888a01cd27e490"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
